spring:
  application:
    name: gateway-service

  cloud:
    config:
      uri: http://localhost:8761

server:
  port: 8080

# spring:
#   application:
#     name: api-gateway
#   cloud:
#     gateway:
#       discovery:
#         locator:
#           enabled: true
#           lower-case-service-id: true
#       routes:               # <-- routes should be inside gateway, not same level
#         - id: user-service
#           uri: lb://USER-SERVICE
#           predicates:
#             - Path=/users/**
#         - id: product-service
#           uri: lb://PRODUCT-SERVICE
#           predicates:
#             - Path=/products/**
#         - id: order-service
#           uri: lb://ORDER-SERVICE
#           predicates:
#             - Path=/orders/**

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
