spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    config:
      uri: http://localhost:8888
  profiles.active: prod

server:
  port: 8084



# server:
#   port: 8084

# spring:
#   application:
#     name: user-service
#   datasource:
#     url: jdbc:mysql://localhost:3306/userdb
#     username: root
#     password: 
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
