spring:
  application:
    name: order-service

  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles.active: prod

server:
  port: 8083

# server:
#   port: 8083

# spring:
#   application:
#     name: order-service
#   datasource:
#     url: jdbc:mysql://localhost:3306/orderdb
#     username: root
#     password: 
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/

# resilience4j:
#   circuitbreaker:
#     instances:
#       userService:
#         slidingWindowSize: 10
#         failureRateThreshold: 50
#         waitDurationInOpenState: 10s
#       productService:
#         slidingWindowSize: 10
#         failureRateThreshold: 50
#         waitDurationInOpenState: 10s
#   retry:
#     instances:
#       userService:
#         maxAttempts: 3
#         waitDuration: 2s
#       productService:
#         maxAttempts: 3
#         waitDuration: 2s

# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"
