spring:
  application:
    name: product-service

  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles.active: prod

server:
  port: 8082

# server:
#   port: 8082

# spring:
#   application:
#     name: product-service
#   datasource:
#     url: jdbc:mysql://localhost:3306/productdb
#     username: root
#     password: 
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
